version: "3.9"
services:
    clinicdb:
        image: "mcr.microsoft.com/mssql/server:2017-latest-ubuntu"
        environment:
            SA_PASSWORD: "ClinicPassword123!"
            ACCEPT_EULA: "Y"
        ports:
          - "1433:1433"
    web:
        build: .
        ports:
          - "8000:80"
        depends_on:
          - clinicdb
    